---
# ------------------------------------------------
# App-of-apps GitOps source
# ------------------------------------------------

# set to true to continue deployment even if child apps fail to sync/healthy
ocp4_app_platform_roi_wait_for_apps_ignore_errors: false

ocp4_app_platform_roi_gitops_repo: https://github.com/redhat-ads-tech/ocp-app-platform-roi-lab-helm.git
ocp4_app_platform_roi_gitops_repo_tag: main

# ------------------------------------------------
# OpenShift Pipelines
# ------------------------------------------------

ocp4_app_platform_roi_openshift_pipelines_namespace: openshift-operators

# ------------------------------------------------
# NooBaa
# ------------------------------------------------

# set to false when deploying on a cluster with ODF installed
ocp4_app_platform_roi_noobaa_install: true
ocp4_app_platform_roi_noobaa_namespace: openshift-storage
ocp4_app_platform_roi_noobaa_name: noobaa

# ------------------------------------------------
# GitLab
# ------------------------------------------------

ocp4_app_platform_roi_gitlab_namespace: gitlab
ocp4_app_platform_roi_gitlab_gitops_name: gitlab

ocp4_app_platform_roi_gitlab_config_smtp_host:
  smtp.gitlab-{{ ocp4_app_platform_roi_gitlab_namespace }}.{{ r_openshift_subdomain }}
ocp4_app_platform_roi_gitlab_config_ssh_host:
  ssh.gitlab-{{ ocp4_app_platform_roi_gitlab_namespace }}.{{ r_openshift_subdomain }}
ocp4_app_platform_roi_gitlab_config_root_password: "{{ common_password }}"
ocp4_app_platform_roi_gitlab_config_host:
  "gitlab-{{ ocp4_app_platform_roi_gitlab_namespace }}.{{ r_openshift_subdomain }}"

ocp4_app_platform_roi_gitlab_users_password: "{{ common_password }}"

# ------------------------------------------------
# Quay
# ------------------------------------------------

ocp4_app_platform_roi_quay_application_name: quay
ocp4_app_platform_roi_quay_namespace: quay-registry

ocp4_app_platform_roi_quay_registry_host: "quay.{{ r_openshift_subdomain }}"
ocp4_app_platform_roi_quay_admin_user: quayadmin
ocp4_app_platform_roi_quay_admin_user_password: "{{ common_password }}"

ocp4_app_platform_roi_quay_organizations:
  - parasol
ocp4_app_platform_roi_quay_users:
  - username: dev1
    email: dev1@rhdh.com
    password: "{{ common_password }}"
  - username: dev2
    email: dev2@rhdh.com
    password: "{{ common_password }}"

# ------------------------------------------------
# LLM / LiteLLM
# ------------------------------------------------

ocp4_app_platform_roi_litellm_api_url: >-
  {{ lookup('agnosticd_user_data', 'litellm_api_base_url') | default('') }}
ocp4_app_platform_roi_litellm_api_key: >-
  {{ lookup('agnosticd_user_data', 'litellm_virtual_key') | default('') }}


# ------------------------------------------------
# Vault
# ------------------------------------------------

ocp4_app_platform_roi_vault_namespace: vault
ocp4_app_platform_roi_vault_name: vault
ocp4_app_platform_roi_vault_auth_namespace: default

# ------------------------------------------------
# External Secrets
# ------------------------------------------------

ocp4_app_platform_roi_external_secrets_namespace: external-secrets

# ------------------------------------------------
# OpenShift Dev Spaces
# ------------------------------------------------

ocp4_app_platform_roi_devspaces_install: true
ocp4_app_platform_roi_devspaces_name: devspaces
ocp4_app_platform_roi_devspaces_namespace: openshift-devspaces

